<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>AiMentor.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AiMentor.Application\AiMentor.Application.csproj" />
    <ProjectReference Include="..\AiMentor.Domain\AiMentor.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
</Project>

